<?php
return [
  'instructor'    => '🧑‍🏫',
  'calendar'      => '📅',
  'alarm'         => '⏰',
  'clock'         => '⏰',
  'email'         => '✉️',
  'phone'         => '📞',
  'money'         => '💸',
  'cash'          => '💶',
  'credit_card'   => '💳',
  'card'          => '💳',
  'billing'       => '💰',
  'total'         => '💰',
  'hour_rate'     => '💸',
  'user'          => '👤',
  'delete'        => '🗑️',
  'edit'          => '✏️',
  'save'          => '💾',
  'info'          => '📝',
];
